### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tobixx** [jakm/txmsgpackrpc#6]
Hi,

do you plan to release a new version already or can I kindly ask to do so ?
These links to Github repositories  (in my packaging) drives me crazy with respect to setuptools and "friends" ...

**Comment by jakm** [comment]
I've just released version [1.2](https://github.com/jakm/txmsgpackrpc/releases/tag/1.2), both pypi sdist and debian package. Have a nice day

**Comment by tobixx** [comment]
Oh great! Thank you!
